// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAOAi0nFQBq9SrfYnKTK-_5SMpkIVaf10',
    appId: '1:719483317475:web:6a141c76efd07058c829d6',
    messagingSenderId: '719483317475',
    projectId: 'delivery-cf26a-20aa3',
    authDomain: 'delivery-cf26a-20aa3.firebaseapp.com',
    storageBucket: 'delivery-cf26a-20aa3.firebasestorage.app',
    measurementId: 'G-NPJP1H26ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYne3uVgKcFjq87a3ilwBFaAd3D3yDRTk',
    appId: '1:719483317475:android:cca12b13b148f178c829d6',
    messagingSenderId: '719483317475',
    projectId: 'delivery-cf26a-20aa3',
    storageBucket: 'delivery-cf26a-20aa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Gozz7LAZV4fSRJGEJ4PrKOUiijhXqRQ',
    appId: '1:719483317475:ios:7ac39b7c60816184c829d6',
    messagingSenderId: '719483317475',
    projectId: 'delivery-cf26a-20aa3',
    storageBucket: 'delivery-cf26a-20aa3.firebasestorage.app',
    iosBundleId: 'com.example.delivery1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Gozz7LAZV4fSRJGEJ4PrKOUiijhXqRQ',
    appId: '1:719483317475:ios:7ac39b7c60816184c829d6',
    messagingSenderId: '719483317475',
    projectId: 'delivery-cf26a-20aa3',
    storageBucket: 'delivery-cf26a-20aa3.firebasestorage.app',
    iosBundleId: 'com.example.delivery1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAOAi0nFQBq9SrfYnKTK-_5SMpkIVaf10',
    appId: '1:719483317475:web:142f96908f09b2f3c829d6',
    messagingSenderId: '719483317475',
    projectId: 'delivery-cf26a-20aa3',
    authDomain: 'delivery-cf26a-20aa3.firebaseapp.com',
    storageBucket: 'delivery-cf26a-20aa3.firebasestorage.app',
    measurementId: 'G-4VTJXNZ97W',
  );
}
